[package]
name = "items"
version = "0.1.0"
authors = ["KennethanCeyer <kenneth@pigno.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
